
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    argument_type_not_assignable: warning
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gql.dart
    - lib/**/*.gql.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    # 強制的に戻り値の型宣言を要求。
    - always_declare_return_types
    # 制御文の本体を新しい行に配置することを要求。
    - always_put_control_body_on_new_line
    # 名前付きパラメータの中で、必須のものを最初に置く。
    - always_put_required_named_parameters_first
    # 名前付きパラメータがnull非許容であることを要求。
    - always_specify_types
    # オーバーライドされたメンバーに@overrideアノテーションを付けることを要求。
    - annotate_overrides
    # dynamic型の使用を避けることを推奨。
    - avoid_annotating_with_dynamic
    # 'as'キーワードの使用を避けることを推奨。
    - avoid_as
    # 条件式でのブールリテラルの使用を避けることを推奨。
    - avoid_bool_literals_in_conditional_expressions
    # 'on'句のないcatchブロックの使用を避けることを推奨。
    - avoid_catches_without_on_clauses
    # エラーをキャッチすることを避けることを推奨。
    - avoid_catching_errors
    # 静的メンバーのみを持つクラスの使用を避けることを推奨。
    - avoid_classes_with_only_static_members
    # doubleとintのチェックを避けることを推奨。
    - avoid_double_and_int_checks
    # 空のelseブロックの使用を避けることを推奨。
    - avoid_empty_else
    # 変更可能なクラスにequalsとhashCodeを実装することを避けることを推奨。
    - avoid_equals_and_hash_code_on_mutable_classes
    # constクラスでフィールドイニシャライザを使用することを避けることを推奨。
    - avoid_field_initializers_in_const_classes
    # foreachコール内の関数リテラルの使用を避けることを推奨
    - avoid_function_literals_in_foreach_calls
    # 値型を実装することを避けることを推奨。
    - avoid_implementing_value_types
    # nullの初期化を避けることを推奨。
    - avoid_init_to_null
    # JavaScriptの丸められた整数を避けることを推奨。
    - avoid_js_rounded_ints
    # 等価演算子でのnullチェックを避けることを推奨。
    - avoid_null_checks_in_equality_operators
    # 位置引数でのブールパラメータの使用を避けることを推奨。
    - avoid_positional_boolean_parameters
    # printの使用を避けることを推奨。
    - avoid_print
    # privateなtypedef関数の使用を避けることを推奨。
    - avoid_private_typedef_functions
    # 相対的なライブラリインポートを避けることを推奨。
    - avoid_relative_lib_imports
  

